export enum ProposeAction {
  FIRST_GROUP = 'FIRST_GROUP',
  QUALIFICATION = 'QUALIFICATION',
  DISPONIBILITY = 'DISPONIBILITE',
  QUALIF_DISPO = 'QUALIF et DISPO',
  CONTRAINTE_SOC = 'CONTRAINTE SOC'
}
