import {CompactType, DisplayGrid, GridsterConfig, GridType} from 'angular-gridster2';

export const GRIDSTER_EMPLOYEE_OPTIONS: GridsterConfig = {
  gridType: GridType.Fit,
  compactType: CompactType.None,
  margin: 0,
  outerMargin: true,
  outerMarginTop: null,
  outerMarginRight: null,
  outerMarginBottom: null,
  outerMarginLeft: null,
  useTransformPositioning: true,
  mobileBreakpoint: 640,
  minCols: 4,
  maxCols: 4,
  minRows: 4,
  maxRows: 4,
  maxItemCols: 100,
  minItemCols: 1,
  maxItemRows: 100,
  minItemRows: 1,
  maxItemArea: 2500,
  minItemArea: 1,
  defaultItemCols: 1,
  defaultItemRows: 1,
  fixedColWidth: 30,
  fixedRowHeight: 70,
  keepFixedHeightInMobile: false,
  keepFixedWidthInMobile: false,
  scrollSensitivity: 10,
  scrollSpeed: 20,
  enableEmptyCellClick: false,
  enableEmptyCellContextMenu: false,
  enableEmptyCellDrop: false,
  enableEmptyCellDrag: false,
  enableOccupiedCellDrop: false,
  emptyCellDragMaxCols: 50,
  emptyCellDragMaxRows: 50,
  ignoreMarginInRow: false,
  draggable: {
    enabled: true
  },
  resizable: {
    enabled: true,
    handles: {s: false, e: true, n: false, w: true, se: false, ne: false, sw: false, nw: false}
  },
  swap: false,
  pushItems: false,
  disablePushOnDrag: false,
  disablePushOnResize: false,
  pushDirections: {north: true, east: true, south: true, west: true},
  pushResizeItems: false,
  displayGrid: DisplayGrid.Always,
  disableWindowResize: false,
  disableWarnings: false,
  scrollToNewItems: false,
  disableScrollVertical: true,
  disableScrollHorizontal: true
};
